spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://localhost:5432/friends_book
    username: postgres
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

admin:
  name: admin
  username: admin@gmail.com
  password: password
