spring:
  datasource:
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgres://@ec2-54-157-66-140.compute-1.amazonaws.com:5432/d35goet03v0c4s
    username: zengyhdyxuheqa
    password: f8f67b8fbd1628bb36ae1f36b04bc4e7e1995aa4514af666efd77aa0ae23736b
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

admin:
  name: admin
  username: admin@gmail.com
  password: password
